language: node_js
node_js:
- 10.8.0
cache:
  directories:
  - client/node_modules
  - server/node_modules
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: chan321ch
  on:
    repo: OlegStotsky/321-ch
script: yarn install && cd server && yarn install && cd .. && yarn test
services:
- mongodb
