language: node_js
node_js:
- 10.8.0
cache:
  directories:
    - "client/node_modules"
    - "server/"
deploy:
  provider: heroku
  api_key:
    secure: odZBFgDtE9Hq7rwakJAI4p7WqaT45vpTdlG++TH//C6Lu0i5eTMt0ErWjgXbPtGlPWUzFH2yaL+w4qavxRu9OWWOP26WwMdGvCrPdwCDXfo7JXYWyoeL1zehmDP2FNXqAifmfyaN2cNHqOZBV2PAk9YWZnaszTZK/q5bCZK7ZCRgXtd8y1HOo/UXehnj4bWUUW9MARcGeXZrpczwPNhs9cvUWOMsGLUpouOhGxgATGDGkqf45JZKk5O/4lWjNsJOiEc5kLn3d03njy4wsBf6CYGGO5JbCOhhL0mZeeH2vyZ8EClzLXBTZML5tLciAomh8YK7RKB4AhTsBIs/Xig6PSLSzTl5/pvGzQiBG6ztnfcauAEh8e67dJn3f0I5kgj88mdBB0YEIZT3toPw0g+9aDOR0ISYfT563oYAt6d6GqYZUwVGg6fp7vqtOl1kKZKZnZguVts3Ivce8n+Z6sOyDYBWFEsFOehoNM9opHGoxhe2izI38djJEICwzwY6hy+CTqGI9assI+jaEu7xNFSzNe+G9atqy0iLQBH44VCKac6rcOWyAvBG0E7S6oA66QjuLd7LlpT3rf3Fd7nZVTEn2kW3QMoubvYMrdXgrO+XwBnemMHPcMtJprzXOpvgp0UxPgd/siSD92/8t6ZwTgsVCSfxPRVtmvZG/I/Pv5X3F3U=
  app: chan321ch
script: yarn install && cd server && yarn install && cd .. && yarn test
services:
- mongodb
