language: node_js
node_js:
- 10.8.0
cache:
  directories:
  - client/node_modules
  - server/node_modules
deploy:
  provider: heroku
  api_key:
    secure: Aacwm8r6VSR/85tt8ZfhufJmfwNVU+zIsU0B/QvJmtvRwSC0NMibte6UPwpfSnqwNoXwJZyzPW+HciY3fNLDW91a/UC0LUdZzdywKU2+jHSEUkcc8KuUHVc2VVeaYM0LA3u5YY9notnE7Yzv5tmu6MSxSATEQoMZ3Ed2uwJZQUvfF0HssA4KYqLg/TInPcwa/kc7iXxBH5GJn9lOOZiN2+HzLZk/l2oRzctcyVwFz/W3mAs0BJiSwHDNHtQ1LhJysn2YM98v35Fg3NRw0M2Nk97HDSk50UX3R8JOwLAFeW4rEzHjuuZ5OWu4c8iyeqJUcvZOOjEOqir0ely/wYbIvbOpu7fLNUaPDwXZPHLSae2ZAAZwGBk4uO3SnyEWPzT349vuuKJ1K5oQE5xQiEaYBWZHxTa0YKqIh2mjrFU9g+mReQs6BUUYYpaeMnpBTBQgi67Yd71eoa0HCWFkSo06M20D3MFVtV7YcxkHMj746YocJwIS7HnfO3gbDQWxlYxeX3LECdZJ+0SQjw67vCg/ToI9W+b59lYGJQrUPBwi3+zhtwytv980gLsOBu4njEMaBRYoBreqrktNypqdys+S6fdqfy5SLN5LdsE9//1lTdkXRFxb6ToWOHEFYbk81bZ9pc8Ef9KWEMyG22M4VUrG1hTTT/3quqiWYVsPznA3lHU=
  app: chan321ch
  on:
    repo: OlegStotsky/321-ch
script: yarn install && cd server && yarn install && cd .. && yarn test
services:
- mongodb
